### ISSUE TITLE
Unable to post new tweets with default settings

### ISSUE THREAD

**Issue by kuttim** [katattakd/KatMirrorBot#1]
Good project!
Slowly started to get into Go lang, tried out your project however  with default settings it seems that a pointer is nil, is this known issue?
The error log itself:
```
Downloading list of "hot" posts on /r/all+popular...
Downloaded 90 posts. Analyzing and filtering posts...
51 posts were usable for image mirroring.
Current posting criteria:
        Minimum upvotes: 8513
        Minimum upvote rate: 1494 upvotes/hour
        Minimum upvote to downvote ratio: 0.9
        Minimum post age: 3h55m52s
        Maximum post age: 9h4m8s
17 / 51 posts met the automatically selected posting critera.
Limiting search depth to 11 posts.

Warn: No unique posts were found.
Uploading  to twitter...
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x0 pc=0x7ff7250a34cd]

goroutine 1 [running]:
main.createTwitterPost(0xc0000104c0, 0x32, 0xc00000c630, 0x2d, 0xc00000e2a0, 0x19, 0xc000010480, 0x32, 0xc000045700, 0x2, ...)
        C:/Users/Mikk/mirror/main.go:426 +0x3ad
main.main()
        C:/Users/Mikk/mirror/main.go:465 +0x39f
exit status 2
```

**Comment by katattakd** [comment]
Oh that's *really* weird. Looking at the code, that *theoretically* shouldn't be a possible state for the program to enter.

https://github.com/katattakd/KatMirrorBot/blob/main/main.go#L406
```golang
fmt.Fprintln(os.Stderr, "\nWarn: No unique posts were found.")
os.Exit(0)
```

Maybe os.Exit() works differently on Windows? I'll look into the issue.

**Comment by kuttim** [comment]
Thanks for replying, still trying to understand how it exactly works - the error actually only happens if I comment `out os.Exit(0)`

I commented it out because I was thinking it would proceed with tweeting the post to twitter itself, but if it's not commented out, it just exits after `os.Exit(0)` (duh) - think I'm missing something here and not sure how to proceed with tweeting the posts to Twitter.

**Comment by katattakd** [comment]
Oh okay. If you're not getting any content to post, you can try increasing the following config values:
- `conf.reddit.analysisdepth` - Changes how strict the bot is with deciding the posting criteria.
- `conf.reddit.searchmultiplier` - Changes how quickly the bot increases the search depth. You can set it to `100` to disable the search depth limiting.

**Comment by kuttim** [comment]
Right, so as per the readme, I'm getting content in posts.csv which start with datapoint `t3_`
E.g
`t3_mxxggo,p:d000f8076805d80bb507c8dd93f007e103f807f825f73ffe27ef37b2ca56f4c0,p:d0f878d8b5cc9307`
And in console, something like this: 
```
Potentially unique post mxxggo found at a post depth of 19 / 20
Downloading image from https://i.redd.it/rwvta6qxy7v61.jpg...
Decoding and hashing rwvta6qxy7v61.jpg...
Skipping post and adding ID to database.
Database now contains 20 post IDs and 38 hashes.
```

Which looks fine to me and it seems like the bot is able to get the popular unique posts - however my question now is that how would I go about tweeting the content which is in the posts.csv?

Sorry if it's hard to understand, English is not my first language.

**Comment by katattakd** [comment]
There should be a message explaining why the bot is skipping a post. Can you please try again with an unmodified version of the software?

**Comment by kuttim** [comment]
Good point, I think the root cause why it skips the posts is that TessBaseAPI seems to be failing to initialize.
```
Warn: Unable to hash image! Error:
 failed to initialize TessBaseAPI with code -1:
```
Which seems to be an issue (most likely), I'll be proceeding to reinstall tesseract and updating this issue accordingly.

Cheers!

**Comment by katattakd** [comment]
This might help you get Tesseract working on Windows: https://github.com/otiai10/gosseract/issues/194#issuecomment-607644612

**Comment by katattakd** [comment]
(I haven't tested this program on Windows yet, so I'm not exactly sure how to get Tesseract working on there. However, if this turns out to be an OS-specific issue, I'll look into getting a copy of Windows and try to fix the issue.)

**Comment by kuttim** [comment]
I can confirm, I didn't have tessdata path added hence the initialization error, it works fine now, thanks!
